drm: add missing dependency to DRM_PANEL_EDP
With CONFIG_DRM_PANEL_EDP=y and CONFIG_DRM_KMS_HELPER=m the compilation
fails:

  drivers/gpu/drm/panel/panel-edp.c:843: undefined reference to `drm_panel_dp_aux_backlight'

Add a dependency on DRM_KMS_HELPER to fix this.

Fixes: 9d6366e743f3 ("drm: fb_helper: improve CONFIG_FB dependency")
Signed-off-by: Luca Weiss <luca@z3ntu.xyz>
Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>